head_node: ecc-head


system_groups:
  - { name: slurm,     gid: 10000 }
  - { name: nsm,       gid: 10001 }
  - { name: data,      gid: 10002 }
  - { name: neuromics, gid: 10003 }
  - { name: bindoff,   gid: 10004 }

system_users:

  - {
      name: slurm,
      uid: 10000,
      group: slurm,
      shell: /sbin/nologin,
      create_home: no,
      group_names: ["nsm", "slurm"],
    }
  - {
      name: brugger,
      uid: 1010,
      group: nsm,
      shell: /bin/bash,
      create_home: yes,
      group_names: ["neuromics", 'wheel', 'admin'],
    }
  - {
      name: melanie,
      uid: 1011,
      group: nsm,
      shell: /bin/bash,
      create_home: yes,
      group_names: ["data", 'admin'],
    }
  - {
      name: gon,
      uid: 1012,
      group: neuromics,
      shell: /bin/bash,
      create_home: yes,
      group_names: [],
    }
  - {
      name: lilah,
      uid: 1013,
      group: neuromics,
      shell: /bin/bash,
      create_home: yes,
      group_names: [],
    }


munge_key: 15dd2f4e7cb41a49b065db2341e7342f


mysql_databases: 
  - name: slurm_acct
  - name: cromwell
mysql_users: 
  - name: slurm
    host: "localhost"
    password: slurm
    priv: "slurm_acct.*:ALL"
  - name: cromwell
    host: localhost
    password: cromwell
    priv: "cromwell.*:ALL"


nsm_tools_version: 0.3.0

cluster_root: /usr/local/

ecc_user: sysadmin

nsm_analysis_root: "{{cluster_root}}/lib/nsm-analysis"
nsm_analysis_user: sysadmin

infrastructure_playbook_root: "{{cluster_root}}/lib/infrastructure-playbook"


influxdb_host: "nsm:8086"
influx_username: nsm
#influx_password: in secret_group_vars/system.vault
influx_database: nsm

# Install the latest version of Telegraf
telegraf_agent_package_state: latest

telegraf_agent_hostname: "{{ inventory_hostname }}"
telegraf_agent_interval: "60" # seconds

telegraf_agent_output:
  - type: influxdb
    config:
      - urls = [ "http://{{ head_node }}:8086/" ]
      - database = "{{ influx_database }}"
      - username = "{{ influx_username }}"
      - password = "{{ influx_password }}"

#example config, needs to be determined later on
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = false
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: chrony

storage:
  neuromics:
  - ppmi
  - natpark
  - parkome1
  - parkome2
  bindoff:
  - polg
