galaxy_info:
  author: Kim Brugger
  description: Manage default linux vm for azure
  company: University of Bergen

  license: MIT

  min_ansible_version: 2.9

  platforms:
  - name: EL
    versions:
    - 7
    - 8

    galaxy_tags:
    - compute

dependencies:

