- hosts: all

  hosts: localhost
  connection: local  
  become: true

  vars_files:
   - group_vars/system.yml

  tasks:
    # need to mount /usr/local before adding stuff to it.
    - name: mount nfs points
      include: tasks/nfs.yml
      tags: "nfs"
    

