roles: 
  - src: geerlingguy.ansible
    version: 2.0.2
  - src: geerlingguy.git
    version: 3.0.0
  - src: geerlingguy.java
    version: 1.10.0
  - src: geerlingguy.pip
    version: 1.3.0
  - src: geerlingguy.repo-epel
    version: 1.3.0
  - src: geerlingguy.mysql
    version: 3.1.0
  - src: weareinteractive.sudo
    version: 1.14.1
  - src: https://github.com/dj-wasabi/ansible-telegraf
    name: dj-wasabi.telegraf
  - src: https://github.com/neuro-sysmed/ansible-role-linux-vm.git
    name: neuro-sysmed.linux-vm

collections:
- name: community.general