
- hosts: head
  become: true
  hosts: localhost
  connection: local

  vars_files:
   - group_vars/system.yml
 #  - secret_group_vars/system.vault    

  tasks:
    - name: add repos
      include: tasks/repos.yml
      tags: repos

    - name: mount nfs points
      include: tasks/nfs.yml
      tags: "nfs"

    - name: Install packages
      include: tasks/base_system.yml
      tags: 'base'

    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'

    - name: configure autofs
      include: tasks/autofs.yml
      tags: autofs


    - name: install slurm head
      include: tasks/slurm_head.yml
      tags: 'slurm'

    - name: install ecc bits
      become: true
      become_user: "{{ecc_user}}"
      include: tasks/ecc.yml
      tags: 'ecc'

    - name: install wdl bits
      become: true
      become_user: "{{ecc_user}}"
      include: tasks/wdl_related.yml
      tags: 'wdl'
      

  roles:
    - geerlingguy.mysql
    - geerlingguy.java
    - dj-wasabi.telegraf
