# this is needed otherwise not all information will be available for creating the slurm config for the controller.
- hosts: all
  become: true
  hosts: localhost
  connection: local

  tags:
    - basesystem

  vars_files:
    - group_vars/system.yml
 
  tasks:
    - name: Install packages
      include: tasks/base_system.yml
      tags: 'base'

    - name: Create users and groups
      include: tasks/users_groups.yml
      tags: 'users'

  roles:
    - dj-wasabi.telegraf
#    - neuromics.linux-vm

- hosts: head
  become: true
  hosts: localhost
  connection: local

  vars_files:
   - group_vars/system.yml
 #  - secret_group_vars/system.vault    

  tasks:
    - name: install slurm head
      include: tasks/slurm_head.yml
      tags: 'slurm'

    - name: install ecc bits
      become: true
      become_user: "{{ecc_user}}"
      include: tasks/ecc.yml
      tags: 'ecc'

    - name: wdl bits
      become: true
      become_user: "{{ecc_user}}"
      include: tasks/wdl_related.yml
      tags: 'wdl'
      
    - name: Install influxdb and grafana
      include: tasks/influxdb.yml
      tags: 'influxdb'


  post_tasks:
    - name: azure bits
      include: tasks/azure_cli.yml
      tags: 'azure'



  roles:
    - geerlingguy.mysql
    - geerlingguy.java

- hosts: node
  become: true

  vars_files:
    group_vars/system.yml

  tasks:
    - name: install slurmd
      include: tasks/slurm_node.yml
      tags: 'slurm'

