- name: configuring autofs for {{group['key']}}

  block:

    - name: set group_name
      set_fact:
        group_name: "{{group['key']}}"

    - name: write /etc/auto.master.d/{{group_name}}.autofs file
      template:
        src: templates/autofs/project.autofs.j2
        dest: /etc/auto.master.d/{{group_name}}.autofs

    - name: write /etc/auto.{{group_name}} file
      template:
        src: templates/autofs/auto.project.j2
        dest: /etc/auto.{{group_name}}

    - name: mkdir /data/{{group_name}}/ directory
      ansible.builtin.file:
        dest: /data/{{group_name}}
        owner: root
        mode: 0755
        state: directory

    - name: write mountpoints to /data/{{group['key']}}/README
      template:
        src: templates/autofs/README.j2
        dest: /data/{{group['key']}}/README
