- name: configuring autofs for scratch

  block:

    - name: write /etc/auto.master.d/scratch.autofs file
      template:
        src: templates/autofs/scratch.autofs.j2
        dest: /etc/auto.master.d/scratch.autofs

    - name: write /etc/auto.scratch file
      template:
        src: templates/autofs/auto.scratch.j2
        dest: /etc/auto.scratch


