---

- name: install requirements
  package:
    name:
      - autofs

- name: configure autofs
  include: tasks/_autofs.yml
  loop: "{{ storage | dict2items }}"
  loop_control:
    loop_var: group



- name: restart autofs
  service:
    name: autofs
    enabled: yes
    state: restarted
