---

- name: install requirements
  package:
    name:
      - autofs

- name: mkdir /data
  file:
    path: /data/
    state: directory
    owner: root
    group: root


- name: mkdir /scratch
  file:
    path: /scratch
    state: directory
    owner: root
    group: root


- name: configure group autofs 
  include: tasks/_autofs.yml
  loop: "{{ storage | dict2items }}"
  loop_control:
    loop_var: group


- name: configure scratch autofs 
  include: tasks/_scratch_autofs.yml


- name: restart autofs
  service:
    name: autofs
    enabled: yes
    state: restarted
