- name: Install and cofigure standard linux vm packages

  block:

    - name: install base packages
      package:
        name:
        - python3.8
        - python3-pip
        - python3.8-venv
        - git
        - gitk
        - jq
        - vim 
        - bzip2
        - aspell-en
        - emacs
        - evolution
        - gimp
        - java-common
        - less 
        - libreoffice
        - locales
        - lsof
        - iotop
        - meld
        - nmap
        - p7zip
        - r-base
        - sqlite3
        - curl
        - wget


    - name: Install microsoft packages
      include_tasks:
        file: microsoft_packages.yml

    - name: check if telegram executable is present
      shell: "which /usr/local/bin/telegram"
      register: telegram_bin
      ignore_errors: true


    - name: download telegram
      get_url:
        url: https://telegram.org/dl/desktop/linux
        dest: /tmp/telegram.tar.tar.xz
      when: telegram_bin.rc != 0
        
    - name: Extract telegram into /usr/local/bin
      ansible.builtin.unarchive:
        src: /tmp/telegram.tar.tar.xz
        dest: /usr/local/bin/
        extra_opts: 
          - --strip-components=1 

    - name: install enviroment module dependencies
      package:
        name:
        - tcl-dev


    - name: check if modules executable is present
      shell: "which /usr/local/bin/modules"
      register: modules_bin
      ignore_errors: true

    - name: build and install modules 5.0.0
      ansible.builtin.shell:  |
        curl -Lo /tmp/modules.tgz https://github.com/cea-hpc/modules/releases/download/v5.0.0/modules-5.0.0.tar.gz
        mkdir -p /tmp/modules
        tar zxvf /tmp/modules.tgz --strip 1 -C /tmp/modules 
        cd /tmp/modules
        ./configure --prefix=/usr/local/  
        make  
        make install  
        rm -rf /tmp/modules*
      when: modules_bin.rc != 0



      
        