- name: Install and cofigure standard linux vm packages

  block:

    - name: install base packages
      package:
        name:
        - python3.8
        - python3-pip
        - python3.8-venv
        - git
        - gitk
        - jq
        - vim 
        - bzip2
        - aspell-en
        - emacs
        - evolution
        - feh
        - gimp
        - java-common
        - less 
        - libreoffice
        - locales
        - lsof
        - iotop
        - meld
        - nmap
        - p7zip
        - r-base
        - sqlite3
        - curl
        - wget


    - name: Install microsoft packages
      include:
        name: microsoft_packages.yml

    - name: check if telegram executable is present
      shell: "which /usr/local/bin/telegram"
      register: telegram_bin
      ignore_errors: true


    - name: download telegram
      get_url:
        url: https://telegram.org/dl/desktop/linux
        dest: /tmp/telegram.tar.tar.xz
      when: telegram_bin.rc != 0
        
    - name: Extract telegram into /usr/local/bin
      ansible.builtin.unarchive:
        src: /tmp/telegram.tar.tar.xz
        dest: /usr/local/bin/
        extra_opts: 
          - --strip-components=1 



      
        