- name: Install and cofigure standard linux vm packages

  block:

    - name: install base packages
      package:
        name:
        - python3.8
        - mlocate
        - python3-pip
        - python3.8-venv
        - python3-pymysql
        - git
        - gitk
        - jq
        - vim 
        - bzip2
        - aspell-en
        - emacs
        - gimp
        - java-common
        - less 
        - libreoffice
        - locales
        - lsof
        - iotop
        - meld
        - nmap
        - p7zip
        - r-base
        - sqlite3
        - curl
        - wget
        - cmake
        - python3-requests
        - python-is-python3
        - mysql-client


    - name: Install microsoft packages
      include_tasks:
        file: microsoft_packages.yml


    # Mainly packages that run auto updating
    - name: Remove base packages
      package:
        name:
        - unattended-upgrades
        - apt-config-auto-update
        - apt-listchanges
        state: absent