- name: Install and cofigure standard linux vm packages

  block:

    - name: install base packages
      package:
        name:
        - python3.8
        - python3-pip
        - python3.8-venv
        - python3-pymysql
        - git
        - gitk
        - jq
        - vim 
        - bzip2
        - aspell-en
        - emacs
        - gimp
        - java-common
        - less 
        - libreoffice
        - locales
        - lsof
        - iotop
        - meld
        - nmap
        - p7zip
        - r-base
        - sqlite3
        - curl
        - wget
        - cmake


    - name: Install microsoft packages
      include_tasks:
        file: microsoft_packages.yml


    - name: Install lmod
      include_tasks:
        file: tasks/lmod.yml


    - name: Install go
      include_tasks:
        file: tasks/go_lang.yml

        