- name: Git checkout of ecc-playbook 
  git:
    repo: 'https://github.com/neuromics/ecc-playbook'
    dest: "{{ infrastructure_playbook_root }}"

- name: create venv in {{ infrastructure_playbook_root }}
  command:
    chdir: "{{  infrastructure_playbook_root }}"
    cmd: python3 -m venv venv
    creates: "{{  infrastructure_playbook_root }}/venv"

- name: Install specified python requirements for ecc-playbook
  pip:
    requirements: "{{  infrastructure_playbook_root }}/requirements.txt"
    virtualenv: "{{  infrastructure_playbook_root }}/venv"

- name: Install specified ansible requirements
  command: "{{  infrastructure_playbook_root }}/venv"
  command: ./venv/bin/ansible-galaxy install -p roles -r requirements.yml
  become: yes
  become_user: "{{ecc_user}}"
  args:
    chdir: "{{ infrastructure_playbook_root }}"
