---
- name: lmod "clients"

  block : 

    - name: install enviroment module dependencies
      package:
        name:
        - lua5.3


    - name: link bash configfile
      ansible.builtin.file:
        src: /usr/local/lmod/lmod/init/profile
        dest: /etc/profile.d/lmod.sh
        state: link
        
    - name: lmod load StdEnv or user default
      ansible.builtin.copy:
        src: files/lmod/lmod_stdenv.sh
        dest: /etc/profile.d/lmod_stdenv.sh

