---
- name: configure lmod

  block : 


    - name: link bash configfile
      ansible.builtin.file:
        src: /usr/local/lmod/lmod/init/profile
        dest: /etc/profile.d/lmod.sh
        state: link
        
    - name: lmod load StdEnv or user default
      ansible.builtin.copy:
        src: files/lomd/lmod_stdenv.sh
        dest: /etc/profile.d/lmod_stdenv.sh

