---
- name: install lmod

  block : 

    - name: install enviroment module dependencies
      package:
        name:
        - lua5.3
        - liblua5.3-dev
        - lua-posix
        - tcl-dev
        - bash
        - make
        - gcc
        
#    - name: check if modules executable is present
#      shell: "module list"
#      register: lmod_bin
#      ignore_errors: true


    - name: Check that the lmod directoy exists
      stat:
        path: /usr/local/lmod/lmod/
      register: lmod_dir
  

    - name: build and install modules 8.5.19
      ansible.builtin.shell:  |
        curl -Lo /tmp/lmod.tgz https://github.com/TACC/Lmod/archive/refs/tags/8.5.19.tar.gz
        mkdir -p /tmp/lmod
        tar zxvf /tmp/lmod.tgz --strip 1 -C /tmp/lmod
        cd /tmp/lmod
        ./configure --prefix=/usr/local
        make  
        make install  
        rm -rf /tmp/lmod*
      when: not lmod_dir.stat.exists

    - name: link bash configfile
      ansible.builtin.file:
        src: /usr/local/lmod/lmod/init/profile
        dest: /etc/profile.d/lmod.sh
        state: link

    - name: copy modulepath file
      ansible.builtin.copy:
        src: files/lmod/modulespath
        dest: /usr/local/lmod/lmod/init/.modulespath
        owner: root
        mode: 0644

    - name: Check that the modulefiles directoy exists
      ansible.builtin.file:
        src: /usr/local/modulefiles/
        mode: 0755
        owner: root
        state: directory

    - name: copy StdEnv file
      ansible.builtin.copy:
        src: files/lmod/StdEnv.lua
        dest: /usr/local/modulefiles/StdEnv.lua
        owner: root
        mode: 0644


    - name: lmod load StdEnv or user default
      ansible.builtin.copy:
        src: files/lomd/lmod_stdenv.sh
        dest: /etc/profile.d/lmod_stdenv.sh

