- name: install modules

    - name: install enviroment module dependencies
      package:
        name:
        - bash
        - gcc
        - grep
        - make
        - runtest
        - sed
        - tcl-dev
        

    - name: check if modules executable is present
      shell: "which /usr/local/bin/modules"
      register: modules_bin
      ignore_errors: true

    - name: build and install modules 5.0.0
      ansible.builtin.shell:  |
        curl -Lo /tmp/modules.tgz https://github.com/cea-hpc/modules/releases/download/v5.0.0/modules-5.0.0.tar.gz
        mkdir -p /tmp/modules
        tar zxvf /tmp/modules.tgz --strip 1 -C /tmp/modules 
        cd /tmp/modules
        ./configure 
        make  
        make install  
        rm -rf /tmp/modules*
      when: modules_bin.rc != 0

    - name: link bash configfile
      ansible.builtin.file:
        src: ln -s /usr/local/Modules/init/profile.sh 
        dest: /etc/profile.d/modules.sh
        state: link
      when: modules_bin.rc != 0

    - name: link csh configfile
      ansible.builtin.file:
        src: ln -s /usr/local/Modules/init/profile.csh 
        dest: /etc/profile.d/modules.csh
        state: link
      when: modules_bin.rc != 0

