---

- name: Install nfs-dependencies
  package:
    name:
      - nfs-common

- name: mkdir /usr/local
  file:
    path: /usr/local
    state: directory
    owner: root
    group: sysadmin
    mode: 0755

- name: unmount /usr/local NFS volume 
  ansible.posix.mount:
    path: /usr/local
    state: unmounted
  ignore_errors: yes



- name: Mount /usr/local NFS volume 
  ansible.posix.mount:
    src: systemfileshare.blob.core.windows.net:/systemfileshare/local
    path: /usr/local
    opts: sec=sys,vers=3,nolock,proto=tcp
    state: mounted
    fstype: nfs
  ignore_errors: yes


- name: mkdir /home/nfs/
  file:
    path: /home/nfs/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: unmount /home/nfs NFS volume 
  ansible.posix.mount:
    path: /home/nfs
    state: unmounted
  ignore_errors: yes


- name: Mount /home NFS volume 
  ansible.posix.mount:
    src: homesfileshare.file.core.windows.net:/homesfileshare/home1
    path: /home/nfs/
    opts: vers=4,minorversion=1,sec=sys
    state: mounted
    fstype: nfs


#- name: mkdir /scratch/neuromics
#  file:
#    path: /scratch/neuromics
#    state: directory
#    owner: root
#    group: sysadmin
#    mode: 0755

#- name: unmount /scratch/neuromics NFS volume 
#  ansible.posix.mount:
#    path: /scratch/neuromics
#    state: unmounted
#  ignore_errors: yes


#- name: Mount /scratch/cromwell NFS volume 
#  ansible.posix.mount:
#    src: neuromics.blob.core.windows.net:/neuromics/scratch
#    path: /scratch/neuromics
#    opts: sec=sys,vers=3,nolock,proto=tcp
#    state: mounted
#    fstype: nfs


#- name: mkdir /scratch/cromwell
#  file:
#    path: /scratch/cromwell
#    state: directory
#    owner: root
#    group: sysadmin
#    mode: 0755

#- name: unmount /scratch/cromwell NFS volume 
#  ansible.posix.mount:
#    path: /scratch/cromwell
#    state: unmounted
#  ignore_errors: yes


#- name: Mount /scratch/cromwell NFS volume 
#  ansible.posix.mount:
#    src: homesfileshare.file.core.windows.net:/homesfileshare/cromwell
#    path: /scratch/cromwell
#    opts: vers=4,minorversion=1,sec=sys
#    state: mounted
#    fstype: nfs

- name: mkdir /refs
  file:
    path: /refs
    state: directory
    owner: root
    group: sysadmin
    mode: 0755

- name: unmount /refs NFS volume 
  ansible.posix.mount:
    path: /refs
    state: unmounted
  ignore_errors: yes


- name: Mount /refs NFS volume 
  ansible.posix.mount:
    src: systemfileshare.blob.core.windows.net:/systemfileshare/refs
    path: /refs
    opts: sec=sys,vers=3,nolock,proto=tcp
    state: mounted
    fstype: nfs
