---
- name: add some non-standard repos

  block:

    - name: Add microsoft signing key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    
    - name: Visual Studio Code repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
        state: present
    

    - name: Add microsoft prod repo (blobfuse)
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod/ {{ansible_distribution_release}} main
        state: present

    - name: Azure-cli repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli {{ansible_distribution_release}} main
        state: present

    - name: Add google signing key
      ansible.builtin.apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: google-chrome repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Add docker signing key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present
        
    - name: Add cloudsmith Erlang signing key
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key
        state: present

    - name: Add cloudsmith rabbitmq signing key
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key
        state: present

    - name: erlang for rabbitmq repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ansible_distribution_release}} main
        state: present

    - name: erlang rabbitmq-server repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ansible_distribution_release}} main
        state: present


    - name: Add nodesource for nodejs/nsm  signing key
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add nodesource for nodejs/nsm  repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://deb.nodesource.com/node_16.x {{ansible_distribution_release}} main
        state: present

    - name: Add influx signing key
      ansible.builtin.apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: Add influx repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://repos.influxdata.com/ubuntu {{ansible_distribution_release}} stable
        state: present

    - name: Add grafana signing key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add grafana  repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.grafana.com/enterprise/deb stable main
        state: present


