---

- name: install slurmctld and slurmdbd
  package:
    name:
      - slurmctld
      - slurmdbd

- name: slurm lib dir
  file:
    path: /var/lib/slurm/
    state: directory
    owner: slurm
    group: slurm



- name: copy slurm conf
  template: 
    src: templates/slurm/slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    mode: 0644
    owner: slurm
    group: slurm
    backup: yes

- name: copy slurmdbd conf
  template: 
    src: templates/slurm/slurmdbd.conf.j2
    dest: /etc/slurm-llnl/slurmdbd.conf
    mode: 0600
    owner: slurm
    group: slurm
    backup: yes

- name: start slurmdbd
  systemd:
    name: slurmdbd
    enabled: true
    state: restarted

- name: start slurmctld
  systemd:
    name: slurmctld
    enabled: true
    state: restarted

#- name: add sysadmin as admin/root
#  command:
#    cmd: sacctmgr -i add user sysadmin AdminLevel=Admin Account=root

