# Dont like this, but works for now
- name: create dynamic slurm node list (debug)
  debug:
    msg:
    - "hostname: {{ item }}"
    - "cores: {{ hostvars[ item ].ansible_processor_cores }}"
    - "CPUs: {{ hostvars[ item ].ansible_processor_count }}"
    - "threads: {{ hostvars[ item ].ansible_processor_threads_per_core }}"
    - "vcpus: {{ hostvars[ item ].ansible_processor_vcpus }}"
    - "mem: {{ hostvars[ item ].ansible_memtotal_mb }}"
  with_items: "{{ groups['node'] }}"



# Dont like this, but works for now
- name: create dynamic slurm node list
  set_fact:
    slurm_nodes: "{{ slurm_nodes|default([]) + [ {'name': item,
                                                  'CoresPerSocket': hostvars[ item ].ansible_processor_cores,
                                                  'Sockets': hostvars[ item ].ansible_processor_count,
                                                  'ThreadsPerCore':  hostvars[ item ].ansible_processor_threads_per_core,
                                                  'CPUs': hostvars[ item ].ansible_processor_vcpus,
                                                  'RealMemory': hostvars[ item ].ansible_memtotal_mb} ] }}"

  with_items: "{{ groups['node'] }}"


- name: copy slurm conf
  template: 
    src: templates/slurm/slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    mode: 0644
    owner: slurm
    group: slurm
    backup: yes


