---
- name: install slurm client 

  block: 

  - name: Install slurm Dependencies
    package:
      name:
        - slurm-client
        - cgroup-tools
        - munge

  - name: add munge key
    copy:
      dest: "/etc/munge/munge.key"
      content: "{{munge_key}}"
      owner: munge
      group: munge
      mode: 0600

  - name: ensure munge is running
    systemd:
      name: munge
      enabled: true
      state: started

  - name: copy cgroup.conf for slurm
    copy:
      src: files/slurm/cgroup.conf
      dest: /etc/slurm-llnl/cgroup.conf
      owner: slurm
      group: slurm
      mode: 0644


  - name: copy slurm conf
    template: 
      src: templates/slurm/slurm.conf.j2
      dest: /etc/slurm-llnl/slurm.conf
      mode: 0644
      owner: slurm
      group: slurm
      backup: yes
