---

- name: copy slurm conf
  template: 
    src: files/slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    mode: 0644
    owner: slurm
    group: slurm
    backup: yes

- name: copy slurmdbd conf
  template: 
    src: files/slurm/slurmdbd.conf
    dest: /etc/slurm/slurmdbd.conf
    mode: 0600
    owner: slurm
    group: slurm
    backup: yes

