
- name: install slurmd
  package:
    name:
      - slurmd


- name: slurm spool dir
  file:
    path: /var/spool/slurm/slurmd
    state: directory
    owner: slurm
    group: slurm



- name: copy slurmdbd conf
  template: 
    src: templates/slurm/slurmdbd.conf.j2
    dest: /etc/slurm-llnl/slurmdbd.conf
    mode: 0600
    owner: slurm
    group: slurm
    backup: yes

- name: start slurmd
  systemd:
    name: slurmd
    enabled: true
    state: restarted
