# .bash_profile

# if running bash
if [ -n "$BASH_VERSION" ]; then
     # include .bashrc if it exists
     if [ -f "$HOME/.bashrc" ]; then
	     . "$HOME/.bashrc"
     fi
fi
# User specific environment and startup programs


# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
	PATH="$HOME/bin:$PATH"
        export PATH
fi

if [ -d "$HOME/.bash_aliases" ] ; then
	. "$HOME/.bash_aliases"
fi


if [ -d "/usr/local/go/bin" ] ; then
	PATH="$PATH:/usr/local/go/bin"
        export PATH
fi
